spring.application.name=backend

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mariadb://localhost:3306/johnData
spring.datasource.username=root
spring.datasource.password=--djkm9Cg0--
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.show-sql= true
